name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install poppler-utils for Windows
        run: |
          Invoke-WebRequest https://github.com/oschwartz10612/poppler-windows/releases/download/v21.08.0/poppler-21.08.0-1-x86_64.zip -OutFile poppler.zip
          Expand-Archive poppler.zip -DestinationPath poppler

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Streamlit app
        run: streamlit run malayalam-ocr-translator.py
